config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount Sidekiq::Web => '/admin/sidekiq'
  root to: 'web/boards#show'

  scope module: :web do
    resource :board, only: :show
    resource :session, only: %i[new create destroy]
    resources :developers, only: %i[new create]
    resource :password_resets, only: %i[new create edit update]
  end

  namespace :admin do
    resources :users
  end

  namespace :api do
    namespace :v1, defaults: { format: 'json' } do
      resources :tasks, only: %i[index show create update destroy] do
        member do
          put :attach_image
          delete :remove_image
        end
      end
      resources :users, only: %i[index show]
    end
  end
end

app/controllers/web/password_resets_controller.rb
class Web::PasswordResetsController < Web::ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params.dig('user', 'email'))

    if @user.present?
      @token = @user.generate_token
      UserMailer.with(user: @user, token: @token).reset_password.deliver_now
      @user.update(reset_password_token_digest: @token)
    end
    redirect_to new_session_path
  end

  def edit
    @user = GlobalID::Locator.locate_signed(params[:token], for: 'password_reset')
    if @user.nil?
      redirect_to new_session_path
    elsif @user.reset_password_token_digest != params[:token]
      redirect_to new_session_path
    end
  end

  def update
    @user = GlobalID::Locator.locate_signed(params[:token], for: 'password_reset')
    if @user.update(password_params.merge(reset_password_token_digest: nil))
      redirect_to new_session_path
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/web/password_resets/edit.html.slim
h4 Reset your password
= simple_form_for :user, url: password_resets_path(token: params[:token]), method: :put do |f|
  p
    = f.input :password
    = f.input :password_confirmation
  p
    = f.button :submit, "Change pass"

app/views/web/password_resets/new.html.slim
h4 Forgot password? No problem!
p Type your email here, we'll send you link.
= simple_form_for :user, url: password_resets_path do |f|
  p
    = f.input :email
  p
    = f.button :submit, "Send"